"use client";

import { useEffect, useRef, type ReactNode } from "react";

/**
 * The fold artwork.
 *
 * The picture itself is a static PNG generated by `scripts/build-mosaic.ts` and
 * committed. Nothing about this fold depends on JavaScript running, on a canvas
 * API, or on an animation firing — if every script on the page fails, the
 * artwork is still there at full fidelity, and if the image request itself
 * fails the plate degrades to a deep sea gradient rather than a white void.
 *
 * On top of that finished image sits one authored motion layer: individual
 * tesserae along the sun's path catching light and letting it go. It is drawn
 * as discrete squares because that is what the artwork is made of — a blurred
 * drifting glow would be a different material pasted over the mosaic. It is
 * purely additive, capped, and it does not run when the visitor has asked for
 * reduced motion.
 */

/** Where the sun sits in the source artwork, in normalised coordinates. */
const SUN_X = 0.36;
const HORIZON = 0.56;

type Glint = {
  x: number;
  y: number;
  size: number;
  born: number;
  life: number;
  peak: number;
};

const MAX_GLINTS = 26;

function makeGlint(now: number, rand: () => number): Glint {
  // Cluster along the sun path: a strong bias to the column under the sun,
  // widening as it comes toward the viewer, which is where the real artwork
  // puts its broken light.
  const depth = HORIZON + rand() * (1 - HORIZON);
  const s = (depth - HORIZON) / (1 - HORIZON);
  const spread = 0.03 + s * 0.2;
  const drift = (rand() + rand() + rand() - 1.5) / 1.5; // bell-ish, centred
  return {
    x: SUN_X + drift * spread,
    y: depth,
    // Tile scale grows with depth, matching the artwork's own ramp.
    size: 4 + Math.pow(s, 1.6) * 16,
    born: now,
    life: 1600 + rand() * 2600,
    peak: 0.2 + rand() * 0.3,
  };
}

export function MosaicFold(): ReactNode {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const reduce = window.matchMedia("(prefers-reduced-motion: reduce)");
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    let raf = 0;
    let glints: Glint[] = [];
    let running = false;

    // Local RNG so the glints never depend on global state and stay cheap.
    let seed = 0x9e37;
    const rand = () => {
      seed = (seed * 1664525 + 1013904223) >>> 0;
      return seed / 4294967296;
    };

    const resize = () => {
      const dpr = Math.min(2, window.devicePixelRatio || 1);
      const { width, height } = canvas.getBoundingClientRect();
      canvas.width = Math.max(1, Math.round(width * dpr));
      canvas.height = Math.max(1, Math.round(height * dpr));
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    };

    const frame = (now: number) => {
      const { width, height } = canvas.getBoundingClientRect();
      ctx.clearRect(0, 0, width, height);

      if (glints.length < MAX_GLINTS && rand() < 0.28) glints.push(makeGlint(now, rand));

      glints = glints.filter((g) => now - g.born < g.life);
      for (const g of glints) {
        const t = (now - g.born) / g.life;
        // Ease in and out so a tile brightens and settles rather than blinking.
        const a = Math.sin(t * Math.PI) * g.peak;
        if (a <= 0.001) continue;
        ctx.fillStyle = `rgba(252, 232, 190, ${a.toFixed(3)})`;
        // Rounded to whole pixels: a tessera has hard edges, and a subpixel
        // rect would render as a soft smudge and break the material.
        ctx.fillRect(
          Math.round(g.x * width),
          Math.round(g.y * height),
          Math.round(g.size),
          Math.round(g.size * 0.72),
        );
      }

      raf = requestAnimationFrame(frame);
    };

    const start = () => {
      if (running || reduce.matches) return;
      running = true;
      resize();
      raf = requestAnimationFrame(frame);
    };

    const stop = () => {
      running = false;
      cancelAnimationFrame(raf);
      const { width, height } = canvas.getBoundingClientRect();
      ctx.clearRect(0, 0, width, height);
    };

    const onMotionChange = () => (reduce.matches ? stop() : start());

    // Idle when scrolled away — no reason to paint an off-screen canvas.
    const io = new IntersectionObserver(
      ([entry]) => (entry?.isIntersecting ? start() : stop()),
      { threshold: 0 },
    );
    io.observe(canvas);

    window.addEventListener("resize", resize);
    reduce.addEventListener("change", onMotionChange);

    return () => {
      io.disconnect();
      window.removeEventListener("resize", resize);
      reduce.removeEventListener("change", onMotionChange);
      cancelAnimationFrame(raf);
    };
  }, []);

  return (
    <div
      className="relative w-full overflow-hidden"
      style={{
        // Fallback material. If the PNG never arrives, this is a deep sea
        // plate — never an empty white band.
        background: "linear-gradient(180deg, #17333e 0%, #0f4a52 58%, #0b2129 100%)",
        // Sized so the nav, the plate and the whole headline band compose one
        // frame: the plate takes whatever the viewport has left after the
        // headline's own height, rather than a fixed fraction that pushes the
        // buttons below the fold on short screens.
        height: "clamp(15rem, calc(100vh - 25rem), 34rem)",
      }}
    >
      {/* eslint-disable-next-line @next/next/no-img-element -- a single
          above-the-fold art plate that must paint immediately and never be
          deferred, resized or lazily swapped by the image pipeline. */}
      <img
        src="/fold-mosaic.png"
        alt="A sunrise over open water, rendered entirely in mosaic tesserae. The tiles nearest the viewer are inscribed with pairs of hexadecimal characters."
        width={2560}
        height={1200}
        fetchPriority="high"
        decoding="async"
        className="h-full w-full object-cover"
        style={{ objectPosition: "50% 54%" }}
      />

      <canvas
        ref={canvasRef}
        aria-hidden="true"
        className="pointer-events-none absolute inset-0 h-full w-full"
      />
    </div>
  );
}
